### ISSUE TITLE
Token holders missing few addresses

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#4381]
> Hello. I've noticed recently that the Token Holders is missing quite a few addresses.

> https://blockscout.com/xdai/mainnet/tokens/0x5426a4d0926d6cd2c003241d8fb1c9420e43ed26/token-holders

> Currently showing 0x1C766e64f1a2F1A8C39977EDd316192166668fbb at the top of the list with 2,930.249 tokens, however the largest liquidity provider is actually 0xd0B5AB1609E1fa7CF6B714Da42e2C9E45e3Ca28D with 3,951.922 tokens. Another example that is missing from the top of the list is 0xbe56543A84a45B1Efe5981A3D43c93dCE7c5f55E

> https://blockscout.com/xdai/mainnet/address/0xd0B5AB1609E1fa7CF6B714Da42e2C9E45e3Ca28D/tokens
https://blockscout.com/xdai/mainnet/address/0xbe56543A84a45B1Efe5981A3D43c93dCE7c5f55E/tokens

> Can someone confirm that this is a bug, or this page is not meant to show all current token holders?

Reference: https://discord.com/channels/502416149343109121/502432256011272195/864446173275619338

**Comment by manavgarg** [comment]
I see this for other contracts too.
For eg: https://blockscout.com/xdai/mainnet/tokens/0xafb1A0C81c848Ad530766aD4BE2fdddC833e1e96/token-holders
this seems to miss some token holders. I believe a lot of the statistics shown are not totally correct.

**Comment by vbaranov** [comment]
@manavgarg how does it look currently? We have deployed an update onto xDai Blockscout instance.

**Comment by manavgarg** [comment]
The issue is still there.
For eg:

Take a list of token holdes here: https://blockscout.com/xdai/mainnet/tokens/0xafb1A0C81c848Ad530766aD4BE2fdddC833e1e96/token-holders
It is missing a holder (address: 0x9d5.. ) which has 31 tokens.

Now, the token holder's page is here which shows the correct value: https://blockscout.com/xdai/mainnet/address/0x9d5a0e8C28d51c45B6aCa82bB1160A70173C3a71/tokens

Is there some sort of caching which is no getting refreshed ?

**Comment by manavgarg** [comment]
Also, if you need help around this or https://github.com/blockscout/blockscout/issues/4203, let me know, I can try looking at the code.
Any helpful pointers as to where to start would be great. Thanks again for your help here :)

**Comment by t12ung** [comment]
The issue which this issue was originally reported for was based on liquidity pool token holders (duplicate of #4380), which seems to have been fixed.

The difference @manavgarg mentions, which is still not resolved is that it's an NFT ERC-721 token.
Token Holders page says `100556 Addresses`. Only 59 addresses shown as holders, so that's **a lot** missing. Should be 2012 pages of results, but currently only has 2 pages.

**Comment by manavgarg** [comment]
Also, the fact that 100556 addresses exist is not correct. There are only ~83k tokens, so this is not even possible. I believe the number of token holders to be in 1000s though.
Some of the inconsistency around this is also captured in https://github.com/blockscout/blockscout/issues/4203.

**Comment by vbaranov** [comment]
There was a delay in indexing a part of the chain in the explorer. Currently, all missed blocks and their data have been successfully processed and should be available via API. I see, that the number of holders of the token instance from the issue has an equal number of holders compared to gnosisscan. I am closing this issue for now.
