### ISSUE TITLE
Verification of some contract works on the sokol block explorer but not on local blockscout instance

### ISSUE THREAD

**Issue by wighawag** [blockscout/blockscout#5149]
Verification of some contract works on the sokol block explorer but not on my local blockscout instance

### Environment

Use docker image generated from this commit : https://github.com/blockscout/blockscout/tree/cae5dd5c500555a7e111d015a164219a39ca0203

### Steps to reproduce

I created a repo : https://github.com/bug-reproduction/blockscout-verification

Instruction here : https://github.com/bug-reproduction/blockscout-verification#readme

```bash
git clone git@github.com:bug-reproduction/blockscout-verification.git
cd blockscout-verification
yarn
```

one terminal:
```bash
yarn dev
```

another terminal
```bash
docker-compose up -d
... PLEASE WAIT SOME TIME
yarn verify localhost --api-url http://localhost:4000 --write-post-data --api-key None
```

### Expected behaviour

The contract should verify succesfully.
They do on etherscan as well as on sokol block explorer

### Actual behaviour

Verification of the smart contract fails with a generic error

**Comment by vbaranov** [comment]
@wighawag What is the generic error look like?

Could you try to build a docker image using the branch from this PR https://github.com/blockscout/blockscout/pull/5136?

**Comment by wighawag** [comment]
I tried with the PR you mentioned but I get the same error :

```
Failed to verify contract GreetingsRegistry: OK, Fail - Unable to verify
```

The other contract verify fine.

You can reproduce the issue by following the reproduction step in https://github.com/bug-reproduction/blockscout-verification

and no useful info appears in blockscout log 

By the way I added a comment to this issue : https://github.com/blockscout/blockscout/issues/5095 
more verbose option for contract verification could help diagnose the issue

**Comment by wighawag** [comment]
@vbaranov 
Let me know if you have more ideas what could go wrong or if I can provide you more info somehow (see https://github.com/blockscout/blockscout/issues/5095)

**Comment by vbaranov** [comment]
@wighawag most likely the issue because Hardhat plugin doesn't support your custom network for verification. For instance, this is how Sokol network has been whitelisted there https://github.com/nomiclabs/hardhat/pull/2122.

**Comment by wighawag** [comment]
@vbaranov this cannot be the case

- I use my own plugin
- I provide the localhost url myself
- it works on one contract and fails on the other

Please see the reproduction repo

Could you reopen ?

**Comment by vbaranov** [comment]
@wighawag 

Ok, the problem is with this task in your reproduction repo, right?
`yarn verify localhost --api-url http://localhost:4000 --write-post-data --api-key None`

According to package.json, `verify` task executes `hardhat etherscan-verify` task, correct?
https://github.com/bug-reproduction/blockscout-verification/blob/ce8e5f827459058839631f05cb9f60c235750d00/_scripts.js#L81
```await execute(`hardhat --network ${network} etherscan-verify ${extra.join(' ')}`);```

The issue is with Hardhat plugin ultimately, isn't it? Then, you should follow this guide to configure hardhat plugin in order to make it compatible with contracts verification in Blockscout https://docs.blockscout.com/for-users/verifying-a-smart-contract/hardhat-verification-plugin.

Correct me, if I am wrong.

**Comment by wighawag** [comment]
> The issue is with Hardhat plugin ultimately, isn't it?

No I use my own plugin : https://github.com/wighawag/hardhat-deploy

And in the repo I also output the data sent to blockscout and you can see that they are exactly the same (except the address) as what I sent to the sokol blockscout instance where it work without problem

**Comment by vbaranov** [comment]
@wighawag could you try to apply this fix https://github.com/blockscout/blockscout/pull/5198 to your local instance?

**Comment by ndnam90** [comment]
Hi @vbaranov, I have same issue when verify hardhat example contract (Greeter) via api, my request param is [here](https://pastebin.com/6a7feZhB)

**Comment by ndnam90** [comment]
@vbaranov
Yes, I tried this fix [#5198](https://github.com/blockscout/blockscout/pull/5198)
I use my custom hardhat which allow verify local chain to get request params, it work on blockscout verify Via standard JSON input page with Try to fetch constructor arguments automatically = Yes, but use this params on API is not working

**Comment by nikitosing** [comment]
@ndnam90 by _these params_ you mean params you shared via pastebin?

**Comment by nikitosing** [comment]
@ndnam90 confirm the issue with the greeter.sol, I will fix it, thanks

**Comment by nikitosing** [comment]
@ndnam90 sorry, I rechecked and I had verified succesfully via latest version of hardhat-etherscan plugin
[link](https://blockscout.com/poa/sokol/address/0x63c0d0A77e1461aca6B41fB16d3Eb2a4EC541E3D/contracts)

**Comment by wighawag** [comment]
@vbaranov 

> @wighawag could you try to apply this fix #5198 to your local instance?

I am getting crash from that commit hash

```
blockscout_1  | ** (Protocol.UndefinedError) protocol Enumerable not implemented for nil of type Atom. This protocol is implemented for the following type(s): Indexer.BoundQueue, Ecto.Adapters.SQL.Stream, Postgrex.Stream, DBConnection.Stream, DBConnection.PrepareStream, Timex.Interval, Flow, Floki.HTMLTree, Jason.OrderedObject, File.Stream, HashDict, List, Map, HashSet, Date.Range, Stream, IO.Stream, MapSet, GenEvent.Stream, Range, Function
blockscout_1  |     (elixir 1.12.3) lib/enum.ex:1: Enumerable.impl_for!/1
blockscout_1  |     (elixir 1.12.3) lib/enum.ex:141: Enumerable.reduce/3
blockscout_1  |     (elixir 1.12.3) lib/enum.ex:3958: Enum.reverse/1
blockscout_1  |     (elixir 1.12.3) lib/keyword.ex:186: Keyword.new/2
blockscout_1  |     (explorer 0.0.1) lib/explorer/repo/config_helper.ex:34: Explorer.Repo.ConfigHelper.extract_parameters/1
blockscout_1  |     (explorer 0.0.1) lib/explorer/repo/config_helper.ex:25: Explorer.Repo.ConfigHelper.get_db_config/1
blockscout_1  |     (explorer 0.0.1) lib/explorer/repo.ex:20: Explorer.Repo.init/2
blockscout_1  |     (ecto 3.7.1) lib/ecto/repo/supervisor.ex:25: Ecto.Repo.Supervisor.runtime_config/4
blockscout_1  | 2022-02-16T21:03:29.047 application=tzdata [info] tzdata release in place is from a file last modified Tue, 22 Dec 2020 23:35:21 GMT. Release file on server was last modified Fri, 22 Oct 2021 02:20:47 GMT.
blockscout_1  | 2022-02-16T21:03:30.182 application=que [info] [Que] Booting Que
blockscout_1  | 2022-02-16T21:03:30.183 application=que [info] [Que] Booting Server Supervisor for Workers
blockscout_1  | 2022-02-16T21:03:30.186 [info] Application explorer exited: Explorer.Application.start(:normal, []) returned an error: shutdown: failed to start child: Explorer.Repo
blockscout_1  |     ** (EXIT) an exception was raised:
blockscout_1  |         ** (Protocol.UndefinedError) protocol Enumerable not implemented for nil of type Atom. This protocol is implemented for the following type(s): Indexer.BoundQueue, Ecto.Adapters.SQL.Stream, Postgrex.Stream, DBConnection.Stream, DBConnection.PrepareStream, Timex.Interval, Flow, Floki.HTMLTree, Jason.OrderedObject, File.Stream, HashDict, List, Map, HashSet, Date.Range, Stream, IO.Stream, MapSet, GenEvent.Stream, Range, Function
blockscout_1  |             (elixir 1.12.3) lib/enum.ex:1: Enumerable.impl_for!/1
blockscout_1  |             (elixir 1.12.3) lib/enum.ex:141: Enumerable.reduce/3
blockscout_1  |             (elixir 1.12.3) lib/enum.ex:3958: Enum.reverse/1
blockscout_1  |             (elixir 1.12.3) lib/keyword.ex:186: Keyword.new/2
blockscout_1  |             (explorer 0.0.1) lib/explorer/repo/config_helper.ex:34: Explorer.Repo.ConfigHelper.extract_parameters/1
blockscout_1  |             (explorer 0.0.1) lib/explorer/repo/config_helper.ex:25: Explorer.Repo.ConfigHelper.get_db_config/1
blockscout_1  |             (explorer 0.0.1) lib/explorer/repo.ex:20: Explorer.Repo.init/2
blockscout_1  |             (ecto 3.7.1) lib/ecto/repo/supervisor.ex:25: Ecto.Repo.Supervisor.runtime_config/4
blockscout_1  | {"Kernel pid terminated",application_controller,"{application_start_failure,explorer,{{shutdown,{failed_to_start_child,'Elixir.Explorer.Repo',{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => nil},[{'Elixir.Enumerable','impl_for!',1,[{file,\"lib/enum.ex\"},{line,1}]},{'Elixir.Enumerable',reduce,3,[{file,\"lib/enum.ex\"},{line,141}]},{'Elixir.Enum',reverse,1,[{file,\"lib/enum.ex\"},{line,3958}]},{'Elixir.Keyword',new,2,[{file,\"lib/keyword.ex\"},{line,186}]},{'Elixir.Explorer.Repo.ConfigHelper',extract_parameters,1,[{file,\"lib/explorer/repo/config_helper.ex\"},{line,34}]},{'Elixir.Explorer.Repo.ConfigHelper',get_db_config,1,[{file,\"lib/explorer/repo/config_helper.ex\"},{line,25}]},{'Elixir.Explorer.Repo',init,2,[{file,\"lib/explorer/repo.ex\"},{line,20}]},{'Elixir.Ecto.Repo.Supervisor',runtime_config,4,[{file,\"lib/ecto/repo/supervisor.ex\"},{line,25}]}]}}},{'Elixir.Explorer.Application',start,[normal,[]]}}}"}
blockscout_1  | Kernel pid terminated (application_controller) ({application_start_failure,explorer,{{shutdown,{failed_to_start_child,'Elixir.Explorer.Repo',{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol
blockscout_1  |
blockscout_1  | Crash dump is being written to: erl_crash.dump...done
blockscout-verification_blockscout_1 exited with code 1
```

**Comment by nikitosing** [comment]
@wighawag I didn't change anything related to the error you sent. Please recheck env variables and configs

**Comment by vbaranov** [comment]
@ndnam90 You should set `gasPrice: 10000000000` in HardHat config for Sokol chain. If you have other questions regarding Hardhat configuration, please ask in Hardhat github repository. This issue is regarding verification in Blockscout through HardHat plugin. Let's keep it clean.

**Comment by ndnam90** [comment]
Thanks @vbaranov, 
I've deployed and verified contract with hardhat to sokol successfully,
Let me check why my local is not woking

**Comment by wighawag** [comment]
> @wighawag I didn't change anything related to the error you sent. Please recheck env variables and configs

Well, I tried again but still getting that crash, and I don't think I changed anything, I documented the process of creating the image and I repeated that here and it fails on that commit : https://github.com/blockscout/blockscout/pull/5198/commits/6d6acfd8ad87b3322ad9e3f29f85b8372daeef69

it also fails on master (commit: https://github.com/blockscout/blockscout/commit/b7e2cb26a82b48354e980168747c594b6289bd5a )

It does not crash on the commit mentioned in the OP :  https://github.com/blockscout/blockscout/tree/cae5dd5c500555a7e111d015a164219a39ca0203

Anything change I should be aware. in the repo I documented the process of building the image, if anything wrong let me know

**Comment by vbaranov** [comment]
@wighawag I followed these steps from the latest master branch commit https://github.com/blockscout/blockscout/commit/e9723772956edf851787112cc0174aeb4c7e83a4 and I have no issues with Docker image creation.

> git clone git@github.com:blockscout/blockscout.git
> cd blockscout
> docker build  -f docker/Dockerfile .

Please try it. If the issue still persists on your end, please share which specific ENV variables you did set (hiding sensitive info)

**Comment by wighawag** [comment]
@vbaranov the issue is not with the image creation, the issue is running it

I use the same command as you mentioned for creating it, without any env variable

As for running, no env variable is set except the one used in the docker-compose : https://github.com/bug-reproduction/blockscout-verification/blob/main/docker-compose.yml

**Comment by vbaranov** [comment]
@wighawag if you use ganache client, you need additionally set:
```
INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: true
```

And,
```
ECTO_USE_SSL: false
```

Here is the working docker-compose.yml in the case of Ganache client https://github.com/blockscout/blockscout/blob/master/docker-compose/docker-compose-no-build-ganache.yml

**Comment by wighawag** [comment]
@vbaranov 

I can confirm that #5198 fixes the issue, Thanks!

as for the docker, it seems since the commit I tested initially there was a change in blockscout that  now requires me to set the following in postgress docker-compose

```
  environment:
    ...
    - POSTGRES_HOST_AUTH_METHOD=trust
```

without it, blockscout instances crashes as described above
