### ISSUE TITLE
Smart contract verification

### ISSUE THREAD

**Issue by Neoblock8** [blockscout/blockscout#7104]
Hi,
 Clone latest blockscout (branch: master), cannot able to verification the contract.
 If we tried to verify the contract, it results "Internal server error". 
 Below mentioned screenshot:
 
 
![image](https://user-images.githubusercontent.com/81068101/226098727-c2a1fe67-8e6e-435c-9e0b-8639c76ef7ce.png)

**Comment by vbaranov** [comment]
@Neoblock8 how did you deploy Blockscout? Through docker-compose? Could you check if you set `SECRET_KEY_BASE`? It is required.

**Comment by Neoblock8** [comment]
> @Neoblock8 how did you deploy Blockscout? Through docker-compose? Could you check if you set `SECRET_KEY_BASE`? It is required.

No, How did we create SECRET_KEY_BASE?

**Comment by vbaranov** [comment]
alphanumeric sequence with min length 64 bytes

**Comment by Neoblock8** [comment]
> alphanumeric sequence with min length 64 bytes

Is there any command for generate SECRET_KEY_BASE?

**Comment by Neoblock8** [comment]
> 

How to create SECRET_KEY_BASE in docker-compose?

**Comment by vbaranov** [comment]
- Run shell in the container
- run `mix phx.gen.secret` inside container
- copy the result of command
- paste the result as the value for SECRET_KEY_BASE
- restart container

**Comment by vbaranov** [comment]
@Neoblock8 is the issue resolved with setting SECRET_KEY_BASE?

**Comment by Neoblock8** [comment]
> @Neoblock8 is the issue resolved with setting SECRET_KEY_BASE?

After given SECRET_KEY_BASE in config file, still cant verify the source code

**Comment by vbaranov** [comment]
Still 503 error? Please provide logs from Blockscout instance.

**Comment by vbaranov** [comment]
@Neoblock8 I am closing the issue. Please open a new issue and provide logs from the instance, if the issue still present.
