### ISSUE TITLE
Broken transaction_actions_protocol Migration

### ISSUE THREAD

**Issue by jtbeckman** [blockscout/blockscout#7473]
Broken migration on v5.1.4:
```
Running migrations for explorer
2023-05-12T20:31:04.902 application=ecto_sql [info] == Running 20230328100414 Explorer.Repo.Migrations.AddTransactionActionTypes.change/0 forward
2023-05-12T20:31:04.906 application=ecto_sql [info] execute "ALTER TYPE transaction_actions_protocol ADD VALUE 'aave_v3'"
** (Postgrex.Error) ERROR 25001 (active_sql_transaction) ALTER TYPE ... ADD cannot run inside a transaction block
    (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.14.0) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:1005: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.10.1) lib/ecto/migration/runner.ex:327: Ecto.Migration.Runner.log_and_execute_ddl/3
    (ecto_sql 3.10.1) lib/ecto/migration/runner.ex:117: anonymous fn/6 in Ecto.Migration.Runner.flush/0
    (elixir 1.14.0) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto_sql 3.10.1) lib/ecto/migration/runner.ex:116: Ecto.Migration.Runner.flush/0
    nofile:1: (file)
```

### Environment

* Deployment type (Manual/Docker/Docker-compose): Docker
* Elixir & Erlang/OTP versions (`elixir -version`): 1.14.4-otp-25
* Node JS version (`node -v`): 18.13.0
* Operating System: Amazon Linux 2
* Blockscout Version/branch/commit: 5.1.4
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): Besu

### Steps to reproduce

Running an init container that runs `bin/blockscout eval "Elixir.Explorer.ReleaseTasks.create_and_migrate()"`

### Expected behaviour

Completed migrations without issue.

### Actual behaviour

We get this error instead:
```
Running migrations for explorer
2023-05-12T20:31:04.902 application=ecto_sql [info] == Running 20230328100414 Explorer.Repo.Migrations.AddTransactionActionTypes.change/0 forward
2023-05-12T20:31:04.906 application=ecto_sql [info] execute "ALTER TYPE transaction_actions_protocol ADD VALUE 'aave_v3'"
** (Postgrex.Error) ERROR 25001 (active_sql_transaction) ALTER TYPE ... ADD cannot run inside a transaction block
    (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.14.0) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:1005: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.10.1) lib/ecto/migration/runner.ex:327: Ecto.Migration.Runner.log_and_execute_ddl/3
    (ecto_sql 3.10.1) lib/ecto/migration/runner.ex:117: anonymous fn/6 in Ecto.Migration.Runner.flush/0
    (elixir 1.14.0) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto_sql 3.10.1) lib/ecto/migration/runner.ex:116: Ecto.Migration.Runner.flush/0
    nofile:1: (file)
```

**Comment by sl1depengwyn** [comment]
Which postgresql version do you use?

**Comment by jtbeckman** [comment]
@sl1depengwyn `11.16`

**Comment by sl1depengwyn** [comment]
> @sl1depengwyn `11.16`

Upgrading to version >= 12 should solve the issue

**Comment by evi1m3** [comment]
HI, I have the same issue with postgres version 14.8 (running from your docker-compose).

**Comment by Fluffynorth** [comment]
on postgres v14 erlang is on 25.3 and elixir is on 1.14.x but still getting this error same as everyone else with a new instance and latest blockscout installation 
/blockscout-backend# mix ecto.migrate
warning: Jason.decode!/1 is undefined (module Jason is not available or is yet to be defined)
  config/config_helper.exs:281: ConfigHelper.parse_json_env_var/2

warning: redefining module ConfigHelper (current version defined in memory)
  config/config_helper.exs:1

warning: Jason.decode!/1 is undefined (module Jason is not available or is yet to be defined)
  config/config_helper.exs:281: ConfigHelper.parse_json_env_var/2

warning: redefining module ConfigHelper (current version defined in memory)
  config/config_helper.exs:1

warning: redefining module ConfigHelper (current version defined in memory)
  config/config_helper.exs:1

warning: redefining module ConfigHelper (current version defined in memory)
  config/config_helper.exs:1


23:41:33.779 [info] == Running 20230328100414 Explorer.Repo.Migrations.AddTransactionActionTypes.change/0 forward

23:41:33.791 [info] execute "ALTER TYPE transaction_actions_protocol ADD VALUE 'aave_v3'"
** (Postgrex.Error) ERROR 25001 (active_sql_transaction) ALTER TYPE ... ADD cannot run inside a transaction block
    (ecto_sql 3.11.3) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.14.4) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql 3.11.3) lib/ecto/adapters/sql.ex:1161: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.11.3) lib/ecto/migration/runner.ex:348: Ecto.Migration.Runner.log_and_execute_ddl/3
    (ecto_sql 3.11.3) lib/ecto/migration/runner.ex:117: anonymous fn/6 in Ecto.Migration.Runner.flush/0
    (elixir 1.14.4) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto_sql 3.11.3) lib/ecto/migration/runner.ex:116: Ecto.Migration.Runner.flush/0
    (ecto_sql 3.11.3) lib/ecto/migration/runner.ex:311: Ecto.Migration.Runner.perform_operation/3
