### ISSUE TITLE
Dockerfile doesn't support am64

### ISSUE THREAD

**Issue by frisitano** [blockscout/blockscout#8521]
*Describe your issue here.*

The base image `bitwalker/alpine-elixir-phoenix:1.14` does not have arm64 builds and as such local builds do not work on macbook M2.  

### Environment

* Deployment type (Manual/Docker/Docker-compose): docker-compose
* Elixir & Erlang/OTP versions (`elixir -version`): elixir: 1.14.0 erlang: 25.0.4 
* Node JS version (`node -v`): 
* Operating System: mac os (arm64 M2 max)
* Blockscout Version/branch/commit: HEAD [1be25fc](https://github.com/blockscout/blockscout/commit/1be25fcf1b54be481eedcb2349a360fef91fc214)
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?):

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

docker-compose build

### Expected behaviour

The blockscout image should be built

### Actual behaviour

Receive a segmentation fault:
```
 => => # qemu: uncaught target signal 11 (Segmentation fault) - core dumped
```

**Comment by ekawibisono** [comment]
hello @frisitano 
Please try modifying the dockerfile with the code below and test whether the same error occurs?
`bitwalker/alpine-elixir-phoenix:1.14` To `hexpm/elixir:1.14.5-erlang-25.3.2.4-alpine-3.18.2`

**Comment by frisitano** [comment]
Hi @ekawibisono I built the `bitwalker/alpine-*` images for arm64 myself and it's now working fine. The image I built is hosted on docker hub at `taulepton/alpine-elixir-phoenix:1.14` however I think a more robust solution should be implemented for other users so they don't have to go through the process of building the images themselves.

**Comment by ekawibisono** [comment]
> Hi @ekawibisono I built the `bitwalker/alpine-*` images for arm64 myself and it's now working fine. The image I built is hosted on docker hub at `taulepton/alpine-elixir-phoenix:1.14` however I think a more robust solution should be implemented for other users so they don't have to go through the process of building the images themselves.

This means that this problem has been resolved with your own solution, right? Let's wait for the blockscout team to respond and review the problem from you even though this problem has been resolved.

**Comment by frisitano** [comment]
> This means that this problem has been resolved with your own solution, right? Let's wait for the blockscout team to respond and review the problem from you even though this problem has been resolved.

I wouldn't consider this problem resolved as the base image `bitwalker/alpine-elixir-phoenix:1.14` does not support arm64 and as such neither does the blockscout docker stack so the issue still holds true even if I have things working for myself.

**Comment by bitwalker** [comment]
arm64 support was temporarily removed due to a bug with Erlang 26 and QEMU, the fix was implemented in QEMU around 2 months ago, and I've been waiting for a release to percolate to package managers so that I can make use of it in my build automation. I'll check to see if that's available now, and if so re-enable arm64 support and get a new set of images published.
