### ISSUE TITLE
Null gas price on Filecoin

### ISSUE THREAD

**Issue by yvaskov** [blockscout/blockscout#9127]
## Description

https://filecoin.blockscout.com/api/v2/stats returns
```
    "gas_prices": {
        "average": null,
        "fast": null,
        "slow": null
    }
```

## Version

[v5.4.0-beta.+commit.26ebc041](https://github.com/blockscout/blockscout/commit/26ebc041)

**Comment by xiang-xx** [comment]
In my case, i found the indexer log about gas price:
```
{
    "time": "2024-01-19T09:04:27.154Z",
    "severity": "error",
    "message": "Couldn't update gas used gas_prices** (ArgumentError) implicit conversion of 6000.0 to Decimal is not allowed. Use Decimal.from_float/1\n    (decimal 2.1.1) lib/decimal.ex:1915: Decimal.decimal/1\n    (decimal 2.1.1) lib/decimal.ex:276: Decimal.add/2\n    (elixir 1.14.5) lib/enum.ex:2468: Enum.\"-reduce/3-lists^foldl/2-0-\"/3\n    (explorer 6.0.0) lib/explorer/chain/cache/gas_price_oracle.ex:302: anonymous fn/1 in Explorer.Chain.Cache.GasPriceOracle.merge_fees/1\n    (elixir 1.14.5) lib/map.ex:258: Map.do_map/2\n    (elixir 1.14.5) lib/map.ex:258: Map.do_map/2\n    (elixir 1.14.5) lib/map.ex:252: Map.new_from_map/2\n    (explorer 6.0.0) lib/explorer/chain/cache/gas_price_oracle.ex:255: Explorer.Chain.Cache.GasPriceOracle.process_fee_data_from_db/1\n",
    "metadata": {
        
    }
}
```

**Comment by yzh-d** [comment]
> In my case, i found the indexer log about gas price:
> 
> ```
> {
>     "time": "2024-01-19T09:04:27.154Z",
>     "severity": "error",
>     "message": "Couldn't update gas used gas_prices** (ArgumentError) implicit conversion of 6000.0 to Decimal is not allowed. Use Decimal.from_float/1\n    (decimal 2.1.1) lib/decimal.ex:1915: Decimal.decimal/1\n    (decimal 2.1.1) lib/decimal.ex:276: Decimal.add/2\n    (elixir 1.14.5) lib/enum.ex:2468: Enum.\"-reduce/3-lists^foldl/2-0-\"/3\n    (explorer 6.0.0) lib/explorer/chain/cache/gas_price_oracle.ex:302: anonymous fn/1 in Explorer.Chain.Cache.GasPriceOracle.merge_fees/1\n    (elixir 1.14.5) lib/map.ex:258: Map.do_map/2\n    (elixir 1.14.5) lib/map.ex:258: Map.do_map/2\n    (elixir 1.14.5) lib/map.ex:252: Map.new_from_map/2\n    (explorer 6.0.0) lib/explorer/chain/cache/gas_price_oracle.ex:255: Explorer.Chain.Cache.GasPriceOracle.process_fee_data_from_db/1\n",
>     "metadata": {
>         
>     }
> }
> ```

I encountered this problem in tag versions v5.2.3-beta and v5.4.0-beta. Have you solved it?

**Comment by sl1depengwyn** [comment]
> In my case, i found the indexer log about gas price:
> 
> ```
> {
>     "time": "2024-01-19T09:04:27.154Z",
>     "severity": "error",
>     "message": "Couldn't update gas used gas_prices** (ArgumentError) implicit conversion of 6000.0 to Decimal is not allowed. Use Decimal.from_float/1\n    (decimal 2.1.1) lib/decimal.ex:1915: Decimal.decimal/1\n    (decimal 2.1.1) lib/decimal.ex:276: Decimal.add/2\n    (elixir 1.14.5) lib/enum.ex:2468: Enum.\"-reduce/3-lists^foldl/2-0-\"/3\n    (explorer 6.0.0) lib/explorer/chain/cache/gas_price_oracle.ex:302: anonymous fn/1 in Explorer.Chain.Cache.GasPriceOracle.merge_fees/1\n    (elixir 1.14.5) lib/map.ex:258: Map.do_map/2\n    (elixir 1.14.5) lib/map.ex:258: Map.do_map/2\n    (elixir 1.14.5) lib/map.ex:252: Map.new_from_map/2\n    (explorer 6.0.0) lib/explorer/chain/cache/gas_price_oracle.ex:255: Explorer.Chain.Cache.GasPriceOracle.process_fee_data_from_db/1\n",
>     "metadata": {
>         
>     }
> }
> ```

What is your Postgresql version?

**Comment by yzh-d** [comment]
> > In my case, i found the indexer log about gas price:
> > ```
> > {
> >     "time": "2024-01-19T09:04:27.154Z",
> >     "severity": "error",
> >     "message": "Couldn't update gas used gas_prices** (ArgumentError) implicit conversion of 6000.0 to Decimal is not allowed. Use Decimal.from_float/1\n    (decimal 2.1.1) lib/decimal.ex:1915: Decimal.decimal/1\n    (decimal 2.1.1) lib/decimal.ex:276: Decimal.add/2\n    (elixir 1.14.5) lib/enum.ex:2468: Enum.\"-reduce/3-lists^foldl/2-0-\"/3\n    (explorer 6.0.0) lib/explorer/chain/cache/gas_price_oracle.ex:302: anonymous fn/1 in Explorer.Chain.Cache.GasPriceOracle.merge_fees/1\n    (elixir 1.14.5) lib/map.ex:258: Map.do_map/2\n    (elixir 1.14.5) lib/map.ex:258: Map.do_map/2\n    (elixir 1.14.5) lib/map.ex:252: Map.new_from_map/2\n    (explorer 6.0.0) lib/explorer/chain/cache/gas_price_oracle.ex:255: Explorer.Chain.Cache.GasPriceOracle.process_fee_data_from_db/1\n",
> >     "metadata": {
> >         
> >     }
> > }
> > ```
> 
> What is your Postgresql version?

The v5.2.3-beta version here corresponds to psql (PostgreSQL) 14.9 (Debian 14.9-1.pgdg120+1), and the v5.4.0-beta version corresponds to psql (PostgreSQL) 14.10 (Debian 14.10-1.pgdg120+1). ), all reported this error

**Comment by sl1depengwyn** [comment]
Could you please share exact error that you face? The gas price oracle mechanism was changed in 6.0.0, so probably your error is gone with the new version

> > > In my case, i found the indexer log about gas price:
> > > ```
> > > {
> > >     "time": "2024-01-19T09:04:27.154Z",
> > >     "severity": "error",
> > >     "message": "Couldn't update gas used gas_prices** (ArgumentError) implicit conversion of 6000.0 to Decimal is not allowed. Use Decimal.from_float/1\n    (decimal 2.1.1) lib/decimal.ex:1915: Decimal.decimal/1\n    (decimal 2.1.1) lib/decimal.ex:276: Decimal.add/2\n    (elixir 1.14.5) lib/enum.ex:2468: Enum.\"-reduce/3-lists^foldl/2-0-\"/3\n    (explorer 6.0.0) lib/explorer/chain/cache/gas_price_oracle.ex:302: anonymous fn/1 in Explorer.Chain.Cache.GasPriceOracle.merge_fees/1\n    (elixir 1.14.5) lib/map.ex:258: Map.do_map/2\n    (elixir 1.14.5) lib/map.ex:258: Map.do_map/2\n    (elixir 1.14.5) lib/map.ex:252: Map.new_from_map/2\n    (explorer 6.0.0) lib/explorer/chain/cache/gas_price_oracle.ex:255: Explorer.Chain.Cache.GasPriceOracle.process_fee_data_from_db/1\n",
> > >     "metadata": {
> > >         
> > >     }
> > > }
> > > ```
> > 
> > 
> > What is your Postgresql version?
> 
> The v5.2.3-beta version here corresponds to psql (PostgreSQL) 14.9 (Debian 14.9-1.pgdg120+1), and the v5.4.0-beta version corresponds to psql (PostgreSQL) 14.10 (Debian 14.10-1.pgdg120+1). ), all reported this error

**Comment by yzh-d** [comment]
> Could you please share exact error that you face? The gas price oracle mechanism was changed in 6.0.0, so probably your error is gone with the new version
> 
> > > > In my case, i found the indexer log about gas price:
> > > > ```
> > > > {
> > > >     "time": "2024-01-19T09:04:27.154Z",
> > > >     "severity": "error",
> > > >     "message": "Couldn't update gas used gas_prices** (ArgumentError) implicit conversion of 6000.0 to Decimal is not allowed. Use Decimal.from_float/1\n    (decimal 2.1.1) lib/decimal.ex:1915: Decimal.decimal/1\n    (decimal 2.1.1) lib/decimal.ex:276: Decimal.add/2\n    (elixir 1.14.5) lib/enum.ex:2468: Enum.\"-reduce/3-lists^foldl/2-0-\"/3\n    (explorer 6.0.0) lib/explorer/chain/cache/gas_price_oracle.ex:302: anonymous fn/1 in Explorer.Chain.Cache.GasPriceOracle.merge_fees/1\n    (elixir 1.14.5) lib/map.ex:258: Map.do_map/2\n    (elixir 1.14.5) lib/map.ex:258: Map.do_map/2\n    (elixir 1.14.5) lib/map.ex:252: Map.new_from_map/2\n    (explorer 6.0.0) lib/explorer/chain/cache/gas_price_oracle.ex:255: Explorer.Chain.Cache.GasPriceOracle.process_fee_data_from_db/1\n",
> > > >     "metadata": {
> > > >         
> > > >     }
> > > > }
> > > > ```
> > > 
> > > 
> > > What is your Postgresql version?
> > 
> > 
> > The v5.2.3-beta version here corresponds to psql (PostgreSQL) 14.9 (Debian 14.9-1.pgdg120+1), and the v5.4.0-beta version corresponds to psql (PostgreSQL) 14.10 (Debian 14.10-1.pgdg120+1). ), all reported this error

The error content in different versions is the same, as shown in the picture below
<img width="1163" alt="image" src="https://github.com/blockscout/blockscout/assets/30540477/c22f970d-d3c8-4c0d-898c-5f31a8adc186">

**Comment by sl1depengwyn** [comment]
From the error I see that you use 6.0.0, your error is known and was fixed

> > Could you please share exact error that you face? The gas price oracle mechanism was changed in 6.0.0, so probably your error is gone with the new version
> > > > > In my case, i found the indexer log about gas price:
> > > > > ```
> > > > > {
> > > > >     "time": "2024-01-19T09:04:27.154Z",
> > > > >     "severity": "error",
> > > > >     "message": "Couldn't update gas used gas_prices** (ArgumentError) implicit conversion of 6000.0 to Decimal is not allowed. Use Decimal.from_float/1\n    (decimal 2.1.1) lib/decimal.ex:1915: Decimal.decimal/1\n    (decimal 2.1.1) lib/decimal.ex:276: Decimal.add/2\n    (elixir 1.14.5) lib/enum.ex:2468: Enum.\"-reduce/3-lists^foldl/2-0-\"/3\n    (explorer 6.0.0) lib/explorer/chain/cache/gas_price_oracle.ex:302: anonymous fn/1 in Explorer.Chain.Cache.GasPriceOracle.merge_fees/1\n    (elixir 1.14.5) lib/map.ex:258: Map.do_map/2\n    (elixir 1.14.5) lib/map.ex:258: Map.do_map/2\n    (elixir 1.14.5) lib/map.ex:252: Map.new_from_map/2\n    (explorer 6.0.0) lib/explorer/chain/cache/gas_price_oracle.ex:255: Explorer.Chain.Cache.GasPriceOracle.process_fee_data_from_db/1\n",
> > > > >     "metadata": {
> > > > >         
> > > > >     }
> > > > > }
> > > > > ```
> > > > 
> > > > 
> > > > What is your Postgresql version?
> > > 
> > > 
> > > The v5.2.3-beta version here corresponds to psql (PostgreSQL) 14.9 (Debian 14.9-1.pgdg120+1), and the v5.4.0-beta version corresponds to psql (PostgreSQL) 14.10 (Debian 14.10-1.pgdg120+1). ), all reported this error
> 
> The error content in different versions is the same, as shown in the picture below <img alt="image" width="1163" src="https://private-user-images.githubusercontent.com/30540477/299258955-c22f970d-d3c8-4c0d-898c-5f31a8adc186.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwODgyNDEsIm5iZiI6MTcwNjA4Nzk0MSwicGF0aCI6Ii8zMDU0MDQ3Ny8yOTkyNTg5NTUtYzIyZjk3MGQtZDNjOC00YzBkLTg5OGMtNWYzMWE4YWRjMTg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDA5MTkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2Yzg3OTE5ZDViZDY1YTcxZjg0NmZhNDQ0NzVkZjE4ZTgyMzg4NTQ4NjU5Y2NlMDBlZWM5MWM5M2MyZGI3M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kl4eBAbHyLGEGgIcUybn5nBKDXUOfED6R6DJl_ta_0Y">

**Comment by yzh-d** [comment]
> From the error I see that you use 6.0.0, your error is known and was fixed
> 
> > > Could you please share exact error that you face? The gas price oracle mechanism was changed in 6.0.0, so probably your error is gone with the new version
> > > > > > In my case, i found the indexer log about gas price:
> > > > > > ```
> > > > > > {
> > > > > >     "time": "2024-01-19T09:04:27.154Z",
> > > > > >     "severity": "error",
> > > > > >     "message": "Couldn't update gas used gas_prices** (ArgumentError) implicit conversion of 6000.0 to Decimal is not allowed. Use Decimal.from_float/1\n    (decimal 2.1.1) lib/decimal.ex:1915: Decimal.decimal/1\n    (decimal 2.1.1) lib/decimal.ex:276: Decimal.add/2\n    (elixir 1.14.5) lib/enum.ex:2468: Enum.\"-reduce/3-lists^foldl/2-0-\"/3\n    (explorer 6.0.0) lib/explorer/chain/cache/gas_price_oracle.ex:302: anonymous fn/1 in Explorer.Chain.Cache.GasPriceOracle.merge_fees/1\n    (elixir 1.14.5) lib/map.ex:258: Map.do_map/2\n    (elixir 1.14.5) lib/map.ex:258: Map.do_map/2\n    (elixir 1.14.5) lib/map.ex:252: Map.new_from_map/2\n    (explorer 6.0.0) lib/explorer/chain/cache/gas_price_oracle.ex:255: Explorer.Chain.Cache.GasPriceOracle.process_fee_data_from_db/1\n",
> > > > > >     "metadata": {
> > > > > >         
> > > > > >     }
> > > > > > }
> > > > > > ```
> > > > > 
> > > > > 
> > > > > What is your Postgresql version?
> > > > 
> > > > 
> > > > The v5.2.3-beta version here corresponds to psql (PostgreSQL) 14.9 (Debian 14.9-1.pgdg120+1), and the v5.4.0-beta version corresponds to psql (PostgreSQL) 14.10 (Debian 14.10-1.pgdg120+1). ), all reported this error
> > 
> > 
> > The error content in different versions is the same, as shown in the picture below <img alt="image" width="1163" src="https://private-user-images.githubusercontent.com/30540477/299258955-c22f970d-d3c8-4c0d-898c-5f31a8adc186.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwODgyNDEsIm5iZiI6MTcwNjA4Nzk0MSwicGF0aCI6Ii8zMDU0MDQ3Ny8yOTkyNTg5NTUtYzIyZjk3MGQtZDNjOC00YzBkLTg5OGMtNWYzMWE4YWRjMTg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDA5MTkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2Yzg3OTE5ZDViZDY1YTcxZjg0NmZhNDQ0NzVkZjE4ZTgyMzg4NTQ4NjU5Y2NlMDBlZWM5MWM5M2MyZGI3M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kl4eBAbHyLGEGgIcUybn5nBKDXUOfED6R6DJl_ta_0Y">

In fact, I am not using version 6.0.0. I am using the two versions mentioned above, and I still get this error.

**Comment by xiang-xx** [comment]
> > In my case, i found the indexer log about gas price:
> > ```
> > {
> >     "time": "2024-01-19T09:04:27.154Z",
> >     "severity": "error",
> >     "message": "Couldn't update gas used gas_prices** (ArgumentError) implicit conversion of 6000.0 to Decimal is not allowed. Use Decimal.from_float/1\n    (decimal 2.1.1) lib/decimal.ex:1915: Decimal.decimal/1\n    (decimal 2.1.1) lib/decimal.ex:276: Decimal.add/2\n    (elixir 1.14.5) lib/enum.ex:2468: Enum.\"-reduce/3-lists^foldl/2-0-\"/3\n    (explorer 6.0.0) lib/explorer/chain/cache/gas_price_oracle.ex:302: anonymous fn/1 in Explorer.Chain.Cache.GasPriceOracle.merge_fees/1\n    (elixir 1.14.5) lib/map.ex:258: Map.do_map/2\n    (elixir 1.14.5) lib/map.ex:258: Map.do_map/2\n    (elixir 1.14.5) lib/map.ex:252: Map.new_from_map/2\n    (explorer 6.0.0) lib/explorer/chain/cache/gas_price_oracle.ex:255: Explorer.Chain.Cache.GasPriceOracle.process_fee_data_from_db/1\n",
> >     "metadata": {
> >         
> >     }
> > }
> > ```
> 
> What is your Postgresql version?

PostgreSQL 12.0 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit

**Comment by xiang-xx** [comment]
> ## Description
> https://filecoin.blockscout.com/api/v2/stats returns
> 
> ```
>     "gas_prices": {
>         "average": null,
>         "fast": null,
>         "slow": null
>     }
> ```
> 
> ## Version
> [v5.4.0-beta.+commit.26ebc041](https://github.com/blockscout/blockscout/commit/26ebc041)

Hi [yvaskov](https://github.com/yvaskov)，I found you api return the gas_prices, how do you fix this? @yvaskov
